### ISSUE TITLE
Consider using map quest tiles as default

### ISSUE THREAD

**Issue by timlinux** [akbargumbira/django-user-map#11]
The HOT OSM tiles don't look so great - it would b nicer to use the MapQuest tiles by default as I think it will create a nicer impression. See:

http://harrywood.co.uk/maps/examples/leaflet/mapquest.view.html

**Comment by akbargumbira** [comment]
Thanks. Addressed here https://github.com/akbargumbira/django-user-map/commit/eec86b17868125abd95296b9eaa1ee7e59c22b5c
